#!/usr/bin/python
#
# Martin Titz, 2025
#
# Shortcut to view many different types of files by
#     v <filename>
#
# Special case
#     v dvd
# looks for a DVD and plays it if found.
#
# Dictionary displayRules defines the mapping file extension to view command.
# Special cases in dictionary by first character
#     '*'    generic rule, will resolved by another lookup in dictionary
#     '%'    command only list contents of file, print initial explaining text
#
# If no matching extension is found or file has no extension, check if file is
# a text file using Unix/Linux file command and in this case display it.
#
# I call for files with txt extension a shell script vf formatting the content
# fitting for size of the terminal window, this script uses a C program winsize.c
#
# See https://github.com/MTitz/Utilities in directory Linux


from os import access, getlogin, R_OK, scandir
from os.path import getsize, isdir, isfile, splitext
from subprocess import DEVNULL, Popen, run
from sys import argv, exit

displayRules = {
    "*audio"  : "vlc",
    "*image"  : "nomacs",
    "*office" : "libreoffice --view",   # office suite files
    "*source" : "less -x4",             # source code, tab space of 4 as guess
    "*text"   : "less",                 # text
    "*video"  : "vlc",

    "7z"      : "%7z l",
    "asm"     : "*source",
    "avi"     : "*video",
    "bas"     : "*source",
    "bat"     : "*source",
    "c"       : "*source",
    "class"   : "%javap",
    "cpp"     : "*source",
    "cs"      : "*source",
    "csh"     : "*source",
    "djvu"    : "evince",
    "doc"     : "*office",              # with special check for plain text file
    "docx"    : "*office",
    "dvi"     : "xdvi",
    "eps"     : "evince",
    "f"       : "*source",
    "f77"     : "*source",
    "f90"     : "*source",
    "f95"     : "*source",
    "fig"     : "xfig",
    "flv"     : "*video",               # Flash Video
    "for"     : "*source",
    "fortran" : "*source",
    "gif"     : "*image",
    "gblorb"  : "gargoyle-free",
    "h"       : "*source",
    "hpp"     : "*source",
    "htm"     : "lynx",
    "html"    : "lynx",
    "ico"     : "*image",
    "jar"     : "%jar tf",
    "java"    : "*source",
    "jpeg"    : "*image",
    "jpg"     : "*image",
    "js"      : "*source",              # JavaScript
    "kra"     : "krita",
    "m4v"     : "*video",
    "mov"     : "*video",
    "mp3"     : "*audio",
    "mp4"     : "*video",
    "mpeg"    : "*audio",
    "odp"     : "*office",              # OpenDocument Presentation
    "ods"     : "*office",              # OpenDocument Spreadsheet
    "odt"     : "*office",              # OpenDocument Text
    "ogg"     : "*audio",
    "pas"     : "*source",              # Pascal
    "pdf"     : "evince",
    "pgn"     : "scid",
    "pl"      : "*source",
    "png"     : "*image",
    "ppt"     : "*office",
    "pptx"    : "*office",
    "ps"      : "evince",
    "py"      : "*source",
    "rar"     : "%rar l",
    "rm"      : "*video",
    "rtf"     : "*office",              # Rich Text Format
    "sh"      : "*source",
    "sqlite"  : "sqlitebrowser -R",
    "svg"     : "*image",
    "tar"     : "%tar tvf",
    "tgz"     : "%tar tvzf",
    "ts"      : "*source",              # TypeScript
    "txt"     : "vf",                   # uses my vf script for formatting too long lines
    "vsd"     : "*office",
    "webp"    : "*image",
    "wma"     : "*audio",
    "wmv"     : "*video",
    "xcf"     : "gimp",
    "xls"     : "*office",
    "xlsx"    : "*office",
    "zip"     : "%unzip -l" }

terminalApps = { "7z", "jar", "javap", "less", "ls", "lynx", "rar", "tar", "unzip", "vf" }


def is_textfile(filename):
    """
    Determines if the given file is a text file by invoking the 'file' command.

    Args:
        filename (str): The path to the file to check.

    Returns:
        bool: True if the file is identified as a text file, False otherwise.
    """
    file_result = run(["file", "-L", filename], capture_output=True)
    if (file_result.returncode != 0):
        return False
    output = file_result.stdout.decode()
    if ':' not in output:
        return False
    return "text" in output.rsplit(':', 1)[1]

def display_file(command, filename):
    args = command.split()
    args.append(filename)
    if args[0] in terminalApps:
        run(args)
    else:
        Popen(args, stderr=DEVNULL)

def display_by_extension(extension, filename):
    # .doc can also be a plain text file, treat as special case
    if extension == "doc":
        command = "*text" if is_textfile(filename) else "*office"
    else:
        command = displayRules[extension]
    if command.startswith("*"):
        if command in displayRules:
            command = displayRules[command]
        else:
            print("Internal error, missing rule for", command)
            exit(2)
    if command.startswith("%"):
        command = command[1:]
        print("Content list for", filename)
        print()
    if command:
        display_file(command, filename)
    else:
        print("Internal error, missing command to extension", extension)
        exit(2)

def playdvd():
    path = "/media/" + getlogin()
    with scandir(path) as it:
        for entry in it:
            if not entry.name.startswith('.') and entry.is_dir():
                dvd_path = path + '/' + entry.name
                if isdir(dvd_path + '/' + "VIDEO_TS"):
                    display_file(displayRules["*video"], dvd_path)
                    return True
    return False


if len(argv) <= 1:
    print("Usage: v <filename>")
    exit(1)
filename = " ".join(argv[1:])
if filename == "dvd":
    if playdvd():
        exit(0)
if isdir(filename):
    print("Content of directory " + filename + ":\n")
    display_file("ls -l", filename)
    exit(0)
elif not isfile(filename):
    print("File", filename, "does not exist.")
    exit(1)
elif not access(filename, R_OK):
    print("File", filename, "is not readable.")
    exit(1)
elif getsize(filename) == 0:
    print("File", filename, "has size 0.")
    exit(0)
extension = splitext(filename)[1][1:]
if len(extension) == 0:
    if is_textfile(filename):
        display_file(displayRules["*text"], filename)
    else:
        print("Filename", filename, "without extension, no rule for displaying.")
        exit(1)
elif extension in displayRules:
    display_by_extension(extension, filename)
elif not extension.islower() and extension.lower() in displayRules:
    display_by_extension(extension.lower(), filename)
else:
    if is_textfile(filename):
        display_file(displayRules["*text"], filename)
    else:
        print("No rule for extension", extension, "to display", filename)
        exit(1)
